version: 2
jobs: 
  build:
    working_dircetory: ~/temp
    docker: 
      - image: circleci/node:8
      - image: mongo:3.4.1
      - image: redis:4.0.1
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: cd server && ls &&  yarn install && npm test
 
