version: 2
jobs: 
  build:
    working_dircetory: ~/temp
    docker: 
      - image: circleci/node:8
    steps:
      - checkout
      - run: cd server
      - run: pwd
      - run: yarn install
      - run: npm test
