version: 2
jobs: 
  build:
    working_dircetory: ~/temp
    docker: 
      - image: circleci/node:8
      - image: mongo:3.4.1
      - image: redis:4.0.1
    steps:
      - checkout

      - run:
          name: Running server test
          command: cd server && ls &&  yarn install 
          - save_cache:
              key: dependency-cache-{{ checksum "package.json" }}
              paths:
                - node_modules
      - run:
          name: Running client test
          command: cd client && ls &&  yarn install 
          - save_cache:
              key: dependency-cache-{{ checksum "package.json" }}
              paths:
                - node_modules
