version: 2
jobs: 
  build:
    working_dircetory: ~/temp
    docker: 
      - image: circleci/node:8
      - image: mongo:3.4.1
      - image: redis:4.0.1
    steps:
      - checkout
      - run:
          name: Running server build
          command: cd server && ls &&  yarn install  
      - run:
          name: Running client build
          command: cd client && ls &&  yarn install  && unset CI npm run deploy 

  test:
    working_dircetory: ~/temp
    docker: 
      - image: circleci/node:8
      - image: mongo:3.4.1
      - image: redis:4.0.1
    steps:
      - checkout

      - run:
          name: Running server test
          command: cd server && ls &&  yarn install && npm run test 
      - run:
          name: Running client test
          command: cd client && ls &&  yarn install  && npm run test 
  deploy:
    working_dircetory: ~/temp
    
    docker: 
      - image: circleci/node:8
      - image: mongo:3.4.1
      - image: redis:4.0.1
    steps:
      - checkout
      - run:
          name: install awscli
          command:  sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: Running server test2
          command: cd server && ls &&  yarn install && npm run test 
      - run:
          name: Running client test2
          command: cd client && ls &&  yarn install  && npm run test
      -run:
        name: final 
        command: aws s3 sync ~/rian s3://rian-s3-dev/ --delete

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master

