version: 2
jobs: 
  build:
    working_dircetory: ~/temp
    docker: 
      - image: circle/node:8
      steps:
        - checkout
        - run: cd server
        - run: yarn install
        - run: npm test
